---
title: "Titanic"
author: "Jonathan Marin"
date: "April 4, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Introduction


# Data



```{r}

library(ggplot2)
library(sqldf)
library(reshape2)

setwd("C:/Users/i64756/Desktop/Kaggle/Titanic")


train <- read.csv("train.csv")

```


# Women and Children First


```{r}

ggplot(train, aes(x=Age, group = Survived, fill = Survived)) +
    geom_histogram(binwidth=5, alpha=.5, position="identity")+   facet_grid(~Survived, labeller = label_both) + theme(legend.position="none")


ggplot(train, aes(x=Sex, group = Survived, fill = Survived)) +
    geom_histogram(stat = "count", binwidth=5, alpha=.5, position="identity")+   facet_grid(~Survived, labeller = label_both) + theme(legend.position="none")


ggplot(train, aes(x=Age, group = Survived, fill = Survived)) +
    geom_histogram(aes(y=(..count..)/sum(..count..)),binwidth=5, alpha=.5, position="identity")+   facet_grid(~Survived, labeller = label_both) + theme(legend.position="none")


ggplot(train, aes(x=Sex, group = Survived, fill = Survived)) +
    geom_histogram(stat = "count", aes(y=(..count..)/sum(..count..)),binwidth=5, alpha=.5, position="identity")+   facet_grid(~Survived, labeller = label_both) + theme(legend.position="none")




```





```

